# Generated by Django 6.0.4 on 2026-04-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
