# Generated by Django 6.0.4 on 2026-04-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ships/'),
        ),
    ]
