# Generated by Django 6.0.4 on 2026-04-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_ship_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
